MAX_MOTORS = 4
POLL_MS_DEFAULT = 250

BTN_W = 120
READ_W = 90
STATUS_W = 280

DEFAULT_STEP_DEG = 5.0
DEFAULT_ACCEL = 10.0
DEFAULT_RAMP_STEP_DEG = 5.0
DEFAULT_SWEEP_STEP_DEG = 5.0

READOUT_UNKNOWN = "--"

DEFAULT_STAGE_SCALE = "PRM1-Z8"
