import os

try:
    from andor.gui import config as andor_cfg
except Exception:
    andor_cfg = None

try:
    from rot.gui import config as rot_cfg
except Exception:
    rot_cfg = None

from measurements.config import DATA_DIR

DEFAULT_STAGE_A_SERIAL = ""
DEFAULT_STAGE_B_SERIAL = ""
DEFAULT_STAGE_SCALE = "PRM1-Z8"

DEFAULT_EXPOSURE_MS = getattr(andor_cfg, "DEFAULT_EXPOSURE_MS", 500.0)
DEFAULT_ACQ_NUMBER = 1
DEFAULT_READOUT_RATE = "2.6MHz at 16-bit"
DEFAULT_PREAMP_GAIN = "4x"
DEFAULT_OUTPUT_AMP = "Conventional"

DEFAULT_SPEC_INDEX = 0
DEFAULT_SLIT_ID = "input_side"
DEFAULT_SLIT_UM = 2500.0
DEFAULT_CENTER_WL_NM = 0.0

if andor_cfg is not None:
    DEFAULT_READOUT_RATE = getattr(andor_cfg, "DEFAULT_READOUT_RATE", DEFAULT_READOUT_RATE)
    DEFAULT_OUTPUT_AMP = getattr(andor_cfg, "DEFAULT_OUTPUT_AMP", DEFAULT_OUTPUT_AMP)
    DEFAULT_SPEC_INDEX = getattr(andor_cfg, "DEFAULT_SPEC_INDEX", DEFAULT_SPEC_INDEX)
    DEFAULT_SLIT_ID = getattr(andor_cfg, "DEFAULT_SLIT_ID", DEFAULT_SLIT_ID)

DEFAULT_FINE_STEP_DEG = 3.0
DEFAULT_RAMP_STEP_DEG = getattr(rot_cfg, "DEFAULT_RAMP_STEP_DEG", 5.0)

DEFAULT_MIN_ANGLE_A = 0.0
DEFAULT_MAX_ANGLE_A = 90.0
DEFAULT_MIN_ANGLE_B = 0.0
DEFAULT_MAX_ANGLE_B = 90.0

DEFAULT_TOTAL_POINTS = 100
DEFAULT_TOTAL_POINTS_MIN = 50
DEFAULT_TOTAL_POINTS_MAX = 300
DEFAULT_BIAS_POWER_FRAC = 0.7
DEFAULT_BIAS_POINT_FRAC = 0.9
DEFAULT_SECOND_HALF_PENALTY = 0.2
DEFAULT_MIN_TRANSMISSION_EPS = 1e-6
DEFAULT_B_COARSE_STEPS = 6
DEFAULT_P00_POWER = 635.0
DEFAULT_A_COARSE_STEPS = 6
DEFAULT_MIN_STEP_NEAR_OPEN_DEG = 1.0
DEFAULT_CLAMP_T_TO_1 = True
DEFAULT_OD_SMOOTH_PTS = 11
DEFAULT_SENS_THRESH = 0.02
DEFAULT_POWER_SPLIT = 0.70
DEFAULT_POINT_SPLIT = 0.90
DEFAULT_MIN_DP_LOW = 1.0
DEFAULT_MIN_DP_HIGH = 5.0
DEFAULT_GOOD_OD_LOW = 0.2
DEFAULT_GOOD_OD_HIGH = 1.2
DEFAULT_GOOD_OD_A_LOW = DEFAULT_GOOD_OD_LOW
DEFAULT_GOOD_OD_A_HIGH = DEFAULT_GOOD_OD_HIGH
DEFAULT_SETTLE_MS = 500
DEFAULT_EPS_SLOPE = 1e-3
DEFAULT_REF_EVERY = 20

DEFAULT_POWER_UNIT = "uW"

DEFAULT_CROP_TOP = 0
DEFAULT_CROP_BOTTOM = 0
DEFAULT_CROP_LEFT = 0
DEFAULT_CROP_RIGHT = 0

DEFAULT_ROI_X1 = 470
DEFAULT_ROI_X2 = 575
DEFAULT_ROI_Y1 = 90
DEFAULT_ROI_Y2 = 150

POLL_MS = 500
