import os

from measurements.config import (
    DEFAULT_ACQ_NUMBER,
    DEFAULT_CENTER_WL_NM,
    DEFAULT_CROP_BOTTOM,
    DEFAULT_CROP_LEFT,
    DEFAULT_CROP_RIGHT,
    DEFAULT_CROP_TOP,
    DEFAULT_EXPOSURE_MS,
    DEFAULT_GRATING,
    DEFAULT_LINECUT_ROW,
    DEFAULT_LINECUT_WIDTH,
    DEFAULT_OUTPUT_AMP,
    DEFAULT_POWER_CALIB_PATH,
    DEFAULT_PREAMP_GAIN,
    DEFAULT_RAMP_STEP_DEG,
    DEFAULT_READOUT_RATE,
    DEFAULT_SLIT_ID,
    DEFAULT_SLIT_UM,
    DEFAULT_SPEC_INDEX,
    DEFAULT_STAGE_ACCEL,
    DEFAULT_STAGE_B_SERIAL,
    DEFAULT_STAGE_SCALE,
    DEFAULT_STAGE_SERIAL,
    POLL_MS,
    DATA_DIR,
)

try:
    from keithley.gui import config as keithley_cfg
except Exception:
    keithley_cfg = None

VISA_DLL = getattr(keithley_cfg, "VISA_DLL", r"C:\\Windows\\System32\\visa64.dll")

DEFAULT_FRONT_RESOURCE = getattr(
    keithley_cfg,
    "DEFAULT_A_RESOURCE",
    "TCPIP0::10.164.14.233::5025::SOCKET",
)
DEFAULT_BACK_RESOURCE = getattr(
    keithley_cfg,
    "DEFAULT_B_RESOURCE",
    "TCPIP0::169.254.153.76::5025::SOCKET",
)

POLL_GATE_MS = 500 # getattr(keithley_cfg, "POLL_MS_DEFAULT", 500)
POLL_TIMEOUT_MS = getattr(keithley_cfg, "POLL_TIMEOUT_MS", 1000)
POLL_ERROR_LIMIT = getattr(keithley_cfg, "POLL_ERROR_LIMIT", 3)

DEFAULT_GATE_VSET = 0.0
DEFAULT_GATE_ICOMP_NA = getattr(keithley_cfg, "DEFAULT_ICOMP_NA", 10.0)

DEFAULT_SWEEP_V0 = 0.0
DEFAULT_SWEEP_STEP = 0.01
DEFAULT_SWEEP_STEPS = 10
DEFAULT_SWEEP_ICOMP_NA = getattr(keithley_cfg, "DEFAULT_SWEEP_ICOMP_NA", 10.0)

RAMP_STEP_V = getattr(keithley_cfg, "RAMP_STEP_V", 0.01)
RAMP_DWELL_S = getattr(keithley_cfg, "RAMP_DWELL_S", 0.10)
SWEEP_SETTLE_MS = 200
ZERO_V_EPS = 1e-4
ZERO_V_EXTRA_SETTLE_MS = 200


READOUT_UNKNOWN = getattr(keithley_cfg, "READOUT_UNKNOWN", "--")

__all__ = [
    "DEFAULT_ACQ_NUMBER",
    "DEFAULT_CENTER_WL_NM",
    "DEFAULT_CROP_BOTTOM",
    "DEFAULT_CROP_LEFT",
    "DEFAULT_CROP_RIGHT",
    "DEFAULT_CROP_TOP",
    "DEFAULT_EXPOSURE_MS",
    "DEFAULT_GRATING",
    "DEFAULT_LINECUT_ROW",
    "DEFAULT_LINECUT_WIDTH",
    "DEFAULT_OUTPUT_AMP",
    "DEFAULT_POWER_CALIB_PATH",
    "DEFAULT_PREAMP_GAIN",
    "DEFAULT_RAMP_STEP_DEG",
    "DEFAULT_READOUT_RATE",
    "DEFAULT_SLIT_ID",
    "DEFAULT_SLIT_UM",
    "DEFAULT_SPEC_INDEX",
    "DEFAULT_STAGE_ACCEL",
    "DEFAULT_STAGE_B_SERIAL",
    "DEFAULT_STAGE_SCALE",
    "DEFAULT_STAGE_SERIAL",
    "POLL_MS",
    "DATA_DIR",
    "VISA_DLL",
    "DEFAULT_FRONT_RESOURCE",
    "DEFAULT_BACK_RESOURCE",
    "POLL_GATE_MS",
    "POLL_TIMEOUT_MS",
    "POLL_ERROR_LIMIT",
    "DEFAULT_GATE_VSET",
    "DEFAULT_GATE_ICOMP_NA",
    "DEFAULT_SWEEP_V0",
    "DEFAULT_SWEEP_STEP",
    "DEFAULT_SWEEP_STEPS",
    "DEFAULT_SWEEP_ICOMP_NA",
    "RAMP_STEP_V",
    "RAMP_DWELL_S",
    "SWEEP_SETTLE_MS",
    "ZERO_V_EPS",
    "ZERO_V_EXTRA_SETTLE_MS",
    "READOUT_UNKNOWN",
]
