BTN_W = 130
READ_W = 140
STATUS_W = 360

DEFAULT_EXPOSURE_MS = 50.0
DEFAULT_EM_GAIN = 0
DEFAULT_HBIN = 1
DEFAULT_VBIN = 1
DEFAULT_TRIGGER = "Internal"
DEFAULT_ACQ_MODE = "Single"
DEFAULT_FRAME_API = "Snap"
DEFAULT_READ_MODE = "Image"
DEFAULT_OUTPUT_AMP = "Conventional"
DEFAULT_READOUT_RATE = "3MHz at 16-bit"
DEFAULT_PREAMP_GAIN = "1x"
DEFAULT_BASELINE_CLAMP = False
DEFAULT_VSHIFT_US = 9.68
DEFAULT_VCLOCK_AMP = "Normal"
DEFAULT_COOLER_ON = True
DEFAULT_SETPOINT_C = -85.0

DEFAULT_SPEC_INDEX = 0
DEFAULT_GRATING = 1
DEFAULT_SLIT_ID = "input_side"
DEFAULT_SLIT_UM = 50.0
DEFAULT_CENTER_WL_NM = 600.0

DEFAULT_LINECUT_WIDTH = 1
